# Generated by Django 3.1.7 on 2021-03-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '커뮤니티 사용자', 'verbose_name_plural': '커뮤니티 사용자'},
        ),
    ]
