# Generated by Django 3.1.7 on 2021-03-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210309_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userEmail',
            field=models.EmailField(default='test@naver.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
